import{a as y,i as c,S}from"./assets/vendor-ee72e1a4.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const a of document.querySelectorAll('link[rel="modulepreload"]'))o(a);new MutationObserver(a=>{for(const n of a)if(n.type==="childList")for(const g of n.addedNodes)g.tagName==="LINK"&&g.rel==="modulepreload"&&o(g)}).observe(document,{childList:!0,subtree:!0});function l(a){const n={};return a.integrity&&(n.integrity=a.integrity),a.referrerPolicy&&(n.referrerPolicy=a.referrerPolicy),a.crossOrigin==="use-credentials"?n.credentials="include":a.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function o(a){if(a.ep)return;a.ep=!0;const n=l(a);fetch(a.href,n)}})();const w="https://pixabay.com/api/",B="44760113-b733d2f51a4c6409aa3483a05";y.defaults.baseURL=w;const i={key:B,q:"str",imageType:"photo",orientation:"horizontal",safesearch:!0};async function h(e){i.q=e;const t=new URLSearchParams(i);return(await y.get(`?${t}&q=${e}&page=1&per_page=15`)).data}c.settings({timeout:2500,resetOnHover:!0,transitionIn:"flipInX",transitionOut:"flipOutX",position:"topRight",titleSize:25,messageSize:25,backgroundColor:"rgba(255, 182, 66, 0.8)"});var v=new S(".gallery a",{captionDelay:200,captionsData:"alt"});const r={formSearchImage:document.querySelector(".uzers-form-image"),gallery:document.querySelector(".gallery"),loadMoreBtn:document.querySelector('[data-action="load-more"]'),spinnerText:document.querySelector(".spinner-text")},b=document.querySelector(".gallery");b.addEventListener("submit",f);function f(e){const t=document.getElementsByClassName(".gallery");t.innerHTML="";const l=e.map(o=>` 
    <li class="gallery-item">
    <a class="gallery-link" href="${o.largeImageURL}">
    <img class="gallery-image" src="${o.webformatURL}" alt="${o.tags}" title="${o.name}"/></a>
    <div class="gallery-paragraf">
    <p class="gallery-commant">likes ${o.likes}</p>
    <p class="gallery-commant">views ${o.views}</p>
    <p class="gallery-commant">comments ${o.comments}</p>
    <p class="gallery-commant">downloads ${o.downloads}</p>
    </div>
    </li> 
     `).join("");b.insertAdjacentHTML("beforeend",l),v.refresh()}function d(e){switch(e){case"outdata":c.warning({title:"Error",message:"Введіть данні для пошуку!"});break;case"nodata":c.warning({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"});break;default:c.error({title:"Error",message:"Щось пішло не так. Ми працюемо над вирішенням питання!"});break}}const m="hidden";function s(e){e.classList.add(m)}function p(e){e.classList.remove(m)}function x(e,t){e.disabled=!0,t.classList.remove(m)}function T(e,t){e.disabled=!1,t.classList.add(m)}s(r.loadMoreBtn);s(r.spinnerText);r.formSearchImage.addEventListener("submit",E);r.loadMoreBtn.addEventListener("click",M);let u="",L=0;async function E(e){if(e.preventDefault(),r.gallery.innerHTML="",i.page=1,u=e.target.searchQuery.value.toLowerCase().trim(),u===""){d("outdata");return}s(r.loadMoreBtn),x(r.loadMoreBtn,r.spinnerText);try{const t=await h(u);if(L=Math.ceil(t.totalHits/i.per_page),t.hits.length>0&&t.hits.length!==t.totalHits)T(r.loadMoreBtn,r.spinnerText);else if(t.hits.length===0){d("nodata"),s(r.loadMoreBtn);return}f(t.hits),p(r.loadMoreBtn),p(r.spinnerText)}catch(t){console.log(t),d(t),s(r.loadMoreBtn),s(r.spinnerText)}finally{e.target.reset(),s(r.spinnerText)}}function M(){i.page+=1,s(r.loadMoreBtn),s(r.spinnerText),setTimeout(async()=>{try{const e=await h(u);f(e.hits);const l=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:l*2,behavior:"smooth"}),p(r.loadMoreBtn)}catch(e){console.log(e),d(e)}finally{i.page===L&&(s(r.loadMoreBtn),s(r.spinnerText),c.error({title:"Error",message:"We're sorry, but you've reached the end of search results."}),r.loadMoreBtn.removeEventListener("click",M))}},500)}
//# sourceMappingURL=commonHelpers.js.map
