import{a as y,i as c,S}from"./assets/vendor-ee72e1a4.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const a of document.querySelectorAll('link[rel="modulepreload"]'))o(a);new MutationObserver(a=>{for(const n of a)if(n.type==="childList")for(const g of n.addedNodes)g.tagName==="LINK"&&g.rel==="modulepreload"&&o(g)}).observe(document,{childList:!0,subtree:!0});function i(a){const n={};return a.integrity&&(n.integrity=a.integrity),a.referrerPolicy&&(n.referrerPolicy=a.referrerPolicy),a.crossOrigin==="use-credentials"?n.credentials="include":a.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function o(a){if(a.ep)return;a.ep=!0;const n=i(a);fetch(a.href,n)}})();const w="https://pixabay.com/api/",M="44760113-b733d2f51a4c6409aa3483a05";y.defaults.baseURL=w;const s={key:M,q:"str",page:1,per_page:15,image_type:"imageType",orientation:"horizontal",safesearch:!0,maxPage:0};async function f(e){s.q=e;const t=new URLSearchParams(s);return(await y.get(`?${t}`)).data}c.settings({timeout:2500,resetOnHover:!0,transitionIn:"flipInX",transitionOut:"flipOutX",position:"topRight",titleSize:25,messageSize:25,backgroundColor:"rgba(255, 182, 66, 0.8)"});var v=new S(".gallery a",{captionDelay:200,captionsData:"alt"});const r={formSearchImage:document.querySelector(".uzers-form-image"),gallery:document.querySelector(".gallery"),loadMoreBtn:document.querySelector('[data-action="load-more"]'),spinnerText:document.querySelector(".spinner-text")},h=document.querySelector(".gallery");h.addEventListener("submit",p);function p(e){const t=document.getElementsByClassName(".gallery");t.innerHTML="";const i=e.map(o=>` 
    <li class="gallery-item">
    <a class="gallery-link" href="${o.largeImageURL}">
    <img class="gallery-image" src="${o.webformatURL}" alt="${o.tags}" title="${o.name}"/></a>
    <div class="gallery-paragraf">
    <p class="gallery-commant">likes ${o.likes}</p>
    <p class="gallery-commant">views ${o.views}</p>
    <p class="gallery-commant">comments ${o.comments}</p>
    <p class="gallery-commant">downloads ${o.downloads}</p>
    </div>
    </li> 
     `).join("");h.insertAdjacentHTML("beforeend",i),v.refresh()}function u(e){switch(e){case"outdata":c.warning({title:"Error",message:"Введіть данні для пошуку!"});break;case"nodata":c.warning({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"});break;default:c.error({title:"Error",message:"Щось пішло не так. Ми працюемо над вирішенням питання!"});break}}const L="hidden";function d(e){e.classList.add(L)}function l(e){e.classList.remove(L)}d(r.loadMoreBtn);d(r.spinnerText);r.formSearchImage.addEventListener("submit",x);r.loadMoreBtn.addEventListener("click",b);let m="";async function x(e){if(e.preventDefault(),m=e.target.searchQuery.value.toLowerCase().trim(),m===""){u("outdata");return}r.gallery.innerHTML="",s.page=1;try{const t=await f(m);if(s.maxPage=Math.ceil(t.hits.total/s.per_page),t.hits.totalHits=500,t.hits.length>0&&t.hits.length===t.hits.totalHits)l(r.loadMoreBtn),l(r.spinnerText);else if(t.hits.length===0){u("nodata");return}p(t.hits),l(r.loadMoreBtn),l(r.spinnerText)}catch(t){console.log(t),u(t)}finally{e.target.reset(),l(r.loadMoreBtn)}}function b(){s.page+=1,d(r.loadMoreBtn),l(r.spinnerText),setTimeout(async()=>{try{const e=await f(m);p(e.hits);const i=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:i*2,behavior:"smooth"}),l(r.loadMoreBtn)}catch(e){console.log(e),u(e)}finally{s.page===s.maxPage&&(d(r.loadMoreBtn),d(r.spinnerText),c.error({title:"Error",message:"We're sorry, but you've reached the end of search results."}),r.loadMoreBtn.removeEventListener("click",b))}},500)}
//# sourceMappingURL=commonHelpers.js.map
